config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[show index]
  resource :profile
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get 'users/show'
  get 'profile', to: 'users#show'
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships
  resources :friend_requests
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 'https://bulma.io/images/placeholders/32x32.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :fname, presence: true
  validates :lname, presence: true
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_post

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        # Tell the UserMailer to send a welcome email after save
        # ProfileMailer.with(profile: @profile).welcome_email.deliver_now

        format.html { redirect_to posts_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to posts_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @profile = current_user.profile
  end

  # Only allow a list of trusted parameters through.
  def profile_params
    params.require(:profile).permit(:fname, :lname, :occupation, :bio, :user_id, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: profile_path, html: { multipart: true }, local: true do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='control'>
  <p class='label'>Profile pic</p>
  <p>
    <%= form.file_field :avatar %>
  </p>
  </div><br>

  <div class="field">
    <div class='control'>
      <%= form.label :fname, 'First name', class: 'label'%>
      <%= form.text_field :fname, class: 'input' %>
    </div class='control'>
  </div>

  <div class="field">
    <div class='control'>
      <%= form.label :lname, 'Last name', class: 'label' %>
      <%= form.text_field :lname, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <div class='control'>
      <%= form.label :occupation, class: 'label' %>
      <%= form.text_field :occupation, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <div class='control'>
      <%= form.label :bio, class: 'label' %>
      <%= form.text_area :bio, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="actions">
    <div class='control'>
      <%= form.submit 'Submit', class: 'button is-info'  %>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class='section'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <h2 class="title is-2">Editing Profile</h2>
        <%= render 'form', profile: @profile %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class='section'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <h2 class="title is-2">New Profile</h2>
        <%= render 'form', profile: @profile %>
      </div>
    </div>
  </div>
</div>