config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[show index]
  resource :profile
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get 'users/show'
  get 'profile', to: 'users#show'
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships
  resources :friend_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

 
  has_many :to_users, foreign_key: 'to_user_id', class_name: 'Friend_request'
  has_many :from_users, foreign_key: 'from_user_id', class_name: 'Friend_request'
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments
  has_one :profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('id != ?', current_user.id)
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/views/users/_post.html.erb
<div class='column is-half'>
  <nav class='panel'>
    <p class='panel-heading'>My Posts</p>
  </nav>
  <% current_user.posts.each do |post| %>
    <div class='box'>    
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= image_tag post.user.profile.avatar.url(:thumb) %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <p class='tag is-info is-small' >
                <%= post.user.profile.fname + ' ' + post.user.profile.lname%>
              </p>
              <br>
                <strong class='title is-4'><%= post.title %></strong>
                <br>
              <%= post.body %>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link_to post, class: "level-item" do %>
                <span class="icon is-small"><i class="fa fa-eye"></i></span>
              <% end %>
              <%= link_to edit_post_path(post), class: "level-item" do %>
                <span class="icon is-small"><i class="fa fa-pencil"></i></span>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: "level-item" do %>
                <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
              <% end %>
              <a class='level-item'>
                <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'like' : 'likes' %>
              </a>
            </div>
          </nav>
        </div>
        <div class="media-right">
          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to post_like_path(post, pre_like), method: :delete do %>
              <span class='icon is-large has-text-info '><i class="far fa-thumbs-down fa fa-2x"></i></span>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(post), method: :post do %>
              <span class='icon is-large has-text-info '><i class="fas fa-thumbs-up fa fa-2x"></i></span>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/users/_profile.html.erb
<div class='section'>
  <div class='columns is-centered'>
    <div class="column is-half">
      <nav class="panel">
        <p class="panel-heading">Profile</p>
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="image is-150x150">
                <%= image_tag current_user.profile.avatar.url(:thumb) %>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= current_user.profile.fname + ' ' + current_user.profile.lname%></strong><br />
                  <% unless current_user.profile.bio.empty? %>
                    <small><%= current_user.profile.bio %></small>
                  <% else %>
                    <small><i>No bio has been made...</i></small>
                  <% end %><br>
                  <small><strong>Occupation:</strong> <%= current_user.profile.occupation %></small>
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="panel-block">
          <div class="level is-mobile">
            <div class="level-item has-centered-text">
              <div>
                <p class="heading">Posts</p>
                <p class="title is-6"><%= current_user.posts.count %></p>
              </div>
            </div>
            <div class="level-item has-centered-text">
              <div>
                <p class="heading">Friends</p>
                <p class="title is-6"><%= current_user.friends.count%></p>
              </div>
            </div>
              <div class="level-item has-centered-text">
              <div>
                <p class="heading">Edit</p>
                <p class="title is-6">
                  <%= link_to edit_profile_path, class: "level-item" do %>
                		<span class="icon is-small"><i class="fa fa-pencil"></i></span>
              		<% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='section'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <h2 class="title is-2">Add a friend</h2><br><br>
          <% @users.each do |user| %>
            <% if user.profile %>
              <% unless current_user.friends.ids.include?(user.id) %>
                <%= user.profile.fname + ' ' + user.profile.lname %>
                <%= form_for FriendRequest.new do %>
                  <%= hidden_field_tag :from_user_id, current_user.id %>
                  <%= hidden_field_tag :to_user_id, user.id%>
                  <%= submit_tag 'Send request', class:'button is-info is-small' %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'profile'%>
<div class='columns is-centered'>
  <%= render 'post' %>
</div>