config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[show index]
  resource :profile
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get 'users/show'
  get 'profile', to: 'users#show'
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships
  resources :friend_requests
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @friends = Friendship.all
    @posts = Post.where(user_id: current_user.friends).or(Post.where(user_id: current_user.id)).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class='control'>
      <%= form.label :title, class: 'label' %>
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <div class='control'>
      <%= form.label :body, class: 'label' %>
      <%= form.text_area :body, class: 'textarea', placeholder: 'Compose a new post...' %>
    </div>
  </div>

  <div class="actions">
    <div class='control'>
      <%= form.submit 'Submit', class: 'button is-info' %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='column is-half'>
  <nav class='panel'>
    <p class='panel-heading'>Posts</p>
  </nav>
  <% @posts.each do |post| %>
    <div class='box'>    
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= image_tag post.user.profile.avatar.url(:thumb) %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <p class='tag is-info is-small' >
                <%= post.user.profile.fname + ' ' + post.user.profile.lname%>
              </p>
              <br>
                <strong class='title is-4'><%= post.title %></strong>
                <br>
              <%= post.body %>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link_to post, class: "level-item" do %>
                <span class="icon is-small"><i class="fa fa-comment fa fa-lg"></i></span>
              <% end %>
              <a class='level-item'>
                <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'like' : 'likes' %>
              </a>
            </div>
          </nav>
        </div>
        <div class="media-right">
          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to post_like_path(post, pre_like), method: :delete do %>
              <span class='icon is-large has-text-info '><i class="far fa-thumbs-down fa fa-2x"></i></span>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(post), method: :post do %>
              <span class='icon is-large has-text-info '><i class="fas fa-thumbs-up fa fa-2x"></i></span>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/posts/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= image_tag current_user.profile.avatar.url(:thumb) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
						  <strong><%= current_user.profile.fname + ' ' + current_user.profile.lname%></strong><br />
                <% unless current_user.profile.bio.empty? %>
                  <small><%= current_user.profile.bio %></small>
                <% else %>
                  <small><i>No bio has been made...</i></small>
                <% end %><br>
                <small><strong>Occupation:</strong> <%= current_user.profile.occupation %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Posts</p>
						<p class="title is-6"><%= current_user.posts.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Friends</p>
						<p class="title is-6"><%= current_user.friends.count%></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Edit</p>
						<p class="title is-6">
							<%= link_to edit_profile_path, class: "level-item" do %>
                <span class="icon is-small"><i class="fa fa-pencil"></i></span>
              <% end %>
						</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/posts/edit.html.erb
<div class='section'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <h2 class='title is-2'>Editing Post</h2>
        <%= render 'form', post: @post %>
        <%= link_to 'Show', @post %> |
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if current_user.profile %>
  <div class='section'>
    <div class='container'>
      <div class='notication'>
        <div class='columns'>
          <%= render 'profile' %>
          <%= render 'post' %>
          <%= render 'friendships/user_friends' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <% controller.redirect_to new_profile_path %>
<% end %>

app/views/posts/new.html.erb
<div class='section'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <h2 class='title is-2'>New Post</h2>
        <%= render 'form', post: @post %>
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class='columns is-centered'>
  <div class='column is-one-quarter'>
    <div class='box'>    
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= image_tag @post.user.profile.avatar.url(:thumb) %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <p class='tag is-info is-small' >
                <%= @post.user.profile.fname + ' ' + @post.user.profile.lname %>
              </p>
              <br>
                <strong class='title is-4'><%= @post.title %></strong>
                <br>
              <%= @post.body %>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <a class='level-item'>
                <%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'like' : 'likes' %>
              </a>
            </div>
          </nav>
        </div>
      </article>
    </div>
  </div>
</div>
<br><br>

<div class='columns is-centered'>
  <div class='column is-half'>
  <h5 class='title is-5'>Comments:</h5><br>
    <%= render @post.comments %><br><br>
    <p><%= @post.comments.count %> Comments</p>
    <%= render 'comments/form' %><br><br>
    <%= link_to 'Back', posts_path %>
  </div>
</div>