config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[show index]
  resource :profile
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get 'users/show'
  get 'profile', to: 'users#show'
  resources :posts do
    resources :likes
    resources :comments
  end
  resources :friendships
  resources :friend_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :to_user, class_name: 'User'
  belongs_to :from_user, class_name: 'User'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def self.create_reciprocal_for_ids(user_id, friend_id)
    user_friendship = Friendship.create(user_id: user_id, friend_id: friend_id)
    friend_friendship = Friendship.create(user_id: friend_id, friend_id: user_id)
    [user_friendship, friend_friendship]
  end

  def self.destroy_reciprocal_for_ids(user_id, friend_id)
    friendship1 = Friendship.find_by(user_id: user_id, friend_id: friend_id)
    friendship2 = Friendship.find_by(user_id: friend_id, friend_id: user_id)
    friendship1.destroy
    friendship2.destroy
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 'https://bulma.io/images/placeholders/32x32.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :fname, presence: true
  validates :lname, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

 
  has_many :to_users, foreign_key: 'to_user_id', class_name: 'Friend_request'
  has_many :from_users, foreign_key: 'from_user_id', class_name: 'Friend_request'
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments
  has_one :profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  
  def create
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params[:comment].permit(:user_id, :comment)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]


  def create
    if already_liked?
      flash[:notice] = 'You cant like more than once'
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to posts_path
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @friends = Friendship.all
    @posts = Post.where(user_id: current_user.friends).or(Post.where(user_id: current_user.id)).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('id != ?', current_user.id)
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
    
    <% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <% if signed_in? %>
          <%= link_to authenticated_root_path, class: "navbar-item" do %>
            <h1 class="title is-5">Odin Facebook</h1>
          <% end %>
        <% else %>
          <%= link_to unauthenticated_root_path, class: "navbar-item" do %>
            <h1 class="title is-5">Odin Facebook</h1>
          <% end %>
        <% end %>
        
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Menu
          </a>
          <div class="navbar-dropdown is-boxed">
            <% if signed_in? %>
              <% if current_user.profile %>
                <a class='navbar-item'>
                  <%= link_to users_show_path, class: "button is-info is-inverted" do %>
                    <i class="fa fa-id-card"> Profile</i>
                  <% end %>
                </a>
                <a class="navbar-item">
                  <%= link_to new_post_path, class: "button is-info is-inverted" do %>
                    <i class="fa fa-plus"> New Post</i>
                  <% end %>
                </a>
                <a class="navbar-item">
                  <%= link_to users_path, class: "button is-info is-inverted" do %>
                    <i class="fa fa-users"> Add a friend</i>
                  <% end %>
                </a>
                <a class="navbar-item">
                  <%= link_to friend_requests_path, class: "button is-info is-inverted" do %>
                    <i class="fa fa-plus-square"> See Friend Requests</i>
                  <% end %>
                </a>
                <a class='navbar-item'>
                  <%= link_to destroy_user_session_path, method: :delete, class: "button is-info is-inverted" do %> 
                    <i class="fa fa-sign-out"> Logout</i>
                  <% end %>
                </a>
              <% else %>
                <a class='navbar-item'>
                  <%= link_to new_profile_path, class: "button is-info is-inverted" do %>
                    <i class="fa fa-id-card"> Create your Profile</i>
                  <% end %>
                </a>
              <% end %>
            <% else %>
              <%= link_to user_facebook_omniauth_authorize_path, class: "button is-info is-inverted" do %>
                <i class="fa fa-facebook-square"> Sign in with Facebook</i>
              <% end %>
              <a class='navbar-item'>
                <%= link_to new_user_registration_path, class: "button is-info is-inverted" do %>
                  <i class="fa fa-user-plus"> Sign Up</i>
                <% end %>
              </a>
              <a class='navbar-item'>
                <%= link_to new_user_session_path, class: "button is-info is-inverted" do %>
                  <i class="fa fa-sign-in"> Sign in</i>
                <% end %>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
    <script type='text/javascript'>
      (function () {
        var burger = document.querySelector('.burger');
        var nav = document.querySelector('#'+burger.dataset.target);

        burger.addEventListener('click', function () {
          burger.classList.toggle('is-active');
          nav.classList.toggle('is-active');
        });
      })();
    </script>
    <%= yield %>
  </body>
   <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>Odin Facebook</strong> by <a href="https://github.com/Alvin-Isai">Alvin Lopez</a>. The source code can be found
          <a href="https://github.com/Alvin-Isai/odin-facebook">here</a>. The website content
          is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </p>
      </div>
    </footer> 
</html>